### ISSUE TITLE
version compare error

### ISSUE THREAD

**Issue by jzyjinziyan** [semver4j/semver4j#234]
Semver semver1 = Semver.parse("1.0.16-lp-zc1-bate+fix-zc1");
    Semver semver2 = Semver.parse("1.0.16-lp-zc1");

    //java.lang.NumberFormatException: For input string: "1-bate"
    System.out.println(semver1.isGreaterThanOrEqualTo(semver2));;

    //java.lang.NumberFormatException: For input string: "1-bate"
    System.out.println(semver1.compareTo(semver2));

**Comment by severn-everett** [comment]
@piotrooo the issue here is that the regex in Comparator.compareIdentifiers() only checks for the presence of one or more digits in the prerelease and doesn't check for whether there are non-digits after said digits:
```java
        if (isBothContainsDigits(a, b)) {
            String digitsExtract = "(?<=\\D)(?=\\d)"; // <= This is producing "1-bate" based on the version string shown above
            String[] tokenArr1 = a.split(digitsExtract);
            String[] tokenArr2 = b.split(digitsExtract);
            if (tokenArr1[0].equals(tokenArr2[0])) {
                long digitA = Long.parseLong(tokenArr1[1]);
                long digitB = Long.parseLong(tokenArr2[1]);
                return compareIdentifiers(digitA, digitB);
            }
        }
```
What would be the best way to resolve this? Wrapping the lines to parse and compare `digitA` and `digitB` in a try/catch for a `NumberFormatException` works, but maybe the regexes in this code block need to be refined instead?

**Comment by piotrooo** [comment]
Many thanks @severn-everett

**Comment by piotrooo** [comment]
I've approved the pull request. 
For future fixes, we can open a separate issue
